{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"order_activity\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1004.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "order_activity": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "order activity": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order_activity": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "activity": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order movement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "order commotion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "movement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "commotion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "order action": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "order motion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "order bustle": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "action": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "motion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bustle": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "order_activity.customer_city": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "customer_city"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer city": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_city": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "city": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer metropolis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer municipality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "metropolis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "municipality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "customer town": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer metropolitan": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "town": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "metropolitan": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "order_activity.customer_zip_code_prefix": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "customer_zip_code_prefix"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer zip code prefix": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_zip_code_prefix": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "prefix": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "code prefix": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "zip code prefix": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "consumer zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "user zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "buyer zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "patron zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchaser zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "shopper zip code prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "customer zip id prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "zip id prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "id prefix": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "order_activity.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Day"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "day": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "order_activity.max_payment_sequential": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "max_payment_sequential"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "max payment sequential": {
                      "State": "Generated"
                    }
                  },
                  {
                    "max_payment_sequential": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "maximum payment sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "max imbursement sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "max compensation sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "max disbursement sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "max sum sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "max expense sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "max recompense sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "max fee sequential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "order_activity.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "order_activity.month_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Month Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "Month": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "order_activity.order_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "order_id"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "order id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order_id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order_purchase_timestamp": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "timestamp": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "timestamp date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "timestamp day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "timestamp month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order purchase timestamp mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase timestamp mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "timestamp mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "timestamp quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order purchase timestamp qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.857
                    }
                  },
                  {
                    "purchase timestamp qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "timestamp qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  }
                ]
              },
              "order_activity.order_purchase_timestamp.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "order_purchase_timestamp"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "order purchase timestamp year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "timestamp year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase timestamp year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order purchase timestamp yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase timestamp yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "timestamp yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "order_activity.order_status": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "order_status"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "order status": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order_status": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "status": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order prestige": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order prominence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "prestige": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "prominence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "order condition": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "order class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "order grade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "order_activity.payment_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "payment_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "payment type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "payment_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "payment category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "payment genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "payment manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "payment variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "payment brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "payment class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "payment kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "order_activity.price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "value": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "penalty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "order_activity.product_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "product_category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product category": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_category": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "category": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "classification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "product class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "product group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "product type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "product grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "product kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "grouping": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "Product": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "order_activity.product_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "product_id"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "product identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "product identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "product credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "artifact id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "order_activity.quantity": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Quantity"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantity": {
                      "State": "Generated"
                    }
                  },
                  {
                    "extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "magnitude": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "measure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "capacity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "mass": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "order_activity.total_order": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Total Orders"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total order": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate order": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall order": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "total command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "order_activity.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "order_activity",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "order_activity_has_customer_city": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.customer_city"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_customer_cities",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.customer_city": {
                    "Target": {
                      "Entity": "order_activity.customer_city"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_customer_zip_code_prefix": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.customer_zip_code_prefix"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_customer_zip_code_prefixes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.customer_zip_code_prefix": {
                    "Target": {
                      "Entity": "order_activity.customer_zip_code_prefix"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_day": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.day"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.day": {
                    "Target": {
                      "Entity": "order_activity.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_max_payment_sequential": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.max_payment_sequential"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_max_payment_sequential",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.max_payment_sequential": {
                    "Target": {
                      "Entity": "order_activity.max_payment_sequential"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_month": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.month"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.month": {
                    "Target": {
                      "Entity": "order_activity.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.month_name"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.month_name": {
                    "Target": {
                      "Entity": "order_activity.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_order_id": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_id"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_order_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.order_id": {
                    "Target": {
                      "Entity": "order_activity.order_id"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_order_purchase_timestamp": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_order_purchase_timestamps",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.order_purchase_timestamp": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_order_status": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_status"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_order_statuses",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.order_status": {
                    "Target": {
                      "Entity": "order_activity.order_status"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_payment_type": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.payment_type"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_payment_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.payment_type": {
                    "Target": {
                      "Entity": "order_activity.payment_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_price": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.price"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "order_activity.price"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "price_indicates_how_expensive_order_activities_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.price": {
                    "Target": {
                      "Entity": "order_activity.price"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_product_category": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.product_category"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_product_categories",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.product_category": {
                    "Target": {
                      "Entity": "order_activity.product_category"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_product_id": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.product_id"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_product_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.product_id": {
                    "Target": {
                      "Entity": "order_activity.product_id"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_quantity": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.quantity"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_quantities",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.quantity": {
                    "Target": {
                      "Entity": "order_activity.quantity"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_total_order": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.total_order"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_total_orders",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.total_order": {
                    "Target": {
                      "Entity": "order_activity.total_order"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_has_year": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.year"
                      },
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "ID": "order_activities_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.year": {
                    "Target": {
                      "Entity": "order_activity.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_in_customer_city": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "ID": "order_activities_are_in_customer_cities",
                    "Preposition": {
                      "Object": {
                        "Role": "order_activity.customer_city"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.customer_city": {
                    "Target": {
                      "Entity": "order_activity.customer_city"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "order_activity.customer_city"
                  }
                },
                "State": "Generated"
              },
              "order_activity_in_customer_zip_code_prefix": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "ID": "order_activities_are_in_customer_zip_code_prefixes",
                    "Preposition": {
                      "Object": {
                        "Role": "order_activity.customer_zip_code_prefix"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "order_activity"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity": {
                    "Target": {
                      "Entity": "order_activity"
                    }
                  },
                  "order_activity.customer_zip_code_prefix": {
                    "Target": {
                      "Entity": "order_activity.customer_zip_code_prefix"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "order_activity.customer_zip_code_prefix"
                  }
                },
                "State": "Generated"
              },
              "order_activity_order_purchase_timestamp_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "order_activity.order_purchase_timestamp"
                      }
                    },
                    "ID": "order_purchase_timestamps_have_order_purchase_timestamp_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity.order_purchase_timestamp": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp"
                    }
                  },
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_order_purchase_timestamp_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                      }
                    },
                    "ID": "order_purchase_timestamp_date_hierarchies_have_order_purchase_timestamp_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                    }
                  },
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_order_purchase_timestamp_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                      }
                    },
                    "ID": "order_purchase_timestamp_date_hierarchies_have_order_purchase_timestamp_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                    }
                  },
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_order_purchase_timestamp_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                      }
                    },
                    "ID": "order_purchase_timestamp_date_hierarchies_have_order_purchase_timestamp_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                    }
                  },
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "order_activity_order_purchase_timestamp_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "order_activity"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                      }
                    },
                    "ID": "order_purchase_timestamp_date_hierarchies_have_order_purchase_timestamp_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy"
                    }
                  },
                  "order_activity.order_purchase_timestamp.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "order_activity.order_purchase_timestamp.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "7e5255e6-e8ab-4387-9bc0-6af49e067c19",
        "fromColumn": "order_purchase_timestamp",
        "fromTable": "order_activity",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d7c68dc3-6768-4511-b150-83cfae3b35d9"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "order_activity",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8d48b78-bdfc-403f-b887-08e28b407acc",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "595078d9-37ce-4a46-b75f-8e3f034c4de0",
            "sourceColumn": "price",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d219120-6361-439b-87e3-2cfc3da8b233",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b80748b1-ef72-44bd-ad13-4ced1fa90f93",
            "sourceColumn": "product_category",
            "summarizeBy": "none"
          },
          {
            "name": "customer_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dba4d6e0-3f04-4d9f-9e44-b1f1025ea30c",
            "sourceColumn": "customer_city",
            "summarizeBy": "none"
          },
          {
            "name": "customer_zip_code_prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe8b69fa-0ef0-4795-ad62-9fb2a63f2a4d",
            "sourceColumn": "customer_zip_code_prefix",
            "summarizeBy": "none"
          },
          {
            "name": "max_payment_sequential",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9db8a8e9-dda3-403a-a46f-aee423d10882",
            "sourceColumn": "max_payment_sequential",
            "summarizeBy": "sum"
          },
          {
            "name": "payment_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ee9e98f-8fd4-4afa-9e17-47e99be16131",
            "sourceColumn": "payment_type",
            "summarizeBy": "none"
          },
          {
            "name": "order_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddcdee41-b57c-4e37-b250-5e0a2f68ce71",
            "sourceColumn": "order_status",
            "summarizeBy": "none"
          },
          {
            "name": "order_purchase_timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "97921f99-846e-4123-90e5-963621ccb77d",
            "sourceColumn": "order_purchase_timestamp",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d7c68dc3-6768-4511-b150-83cfae3b35d9"
                },
                "isDefault": true,
                "relationship": "7e5255e6-e8ab-4387-9bc0-6af49e067c19"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5570b24-a006-4318-a65e-8fc0d3ff1c02",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a079e3ce-c5b1-4a82-9093-94aa24fd7056",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f3d144b-333a-46f2-a32b-a04a39166644",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DISTINCTCOUNT(order_activity[order_id])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2528ea1e-3beb-427b-84d3-c12c4c7946a7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DISTINCTCOUNT(order_activity[product_id]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "483d02ad-a869-4a36-8fa9-02d116be98b7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2b75055-c50b-417d-98d8-44055c1547f8",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b095db9c-956a-4663-8e6a-3626f6f84f6c",
        "partitions": [
          {
            "name": "order_activity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"LAPTOP-P65I9QQH\", \"Portfolio\"),",
                "    dbo_order_activity = Source{[Schema=\"dbo\",Item=\"order_activity\"]}[Data],",
                "    #\"Inserted Month\" = Table.AddColumn(dbo_order_activity, \"Month\", each Date.Month([order_purchase_timestamp]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Month\", \"Month Name\", each Date.MonthName([order_purchase_timestamp]), type text),",
                "    #\"Extracted First Characters\" = Table.TransformColumns(#\"Inserted Month Name\", {{\"Month Name\", each Text.Start(_, 3), type text}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Extracted First Characters\", \"Year\", each Date.Year([order_purchase_timestamp]), Int64.Type),",
                "    #\"Inserted Day\" = Table.AddColumn(#\"Inserted Year\", \"Day\", each Date.Day([order_purchase_timestamp]), Int64.Type)",
                "in",
                "    #\"Inserted Day\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_4bec28dd-0ea3-48ea-baaf-385204515e56",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a2030585-a28a-4b2e-9809-6a9d80ab44a1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8c6a8693-b1d0-48e0-81fe-0a8181a683be",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "595d94fc-d581-418d-a2d4-c4d7a0c199d9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "06ac663e-bc04-4ae1-b19e-ce4084a3481c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd6f3288-1175-436d-855b-0d06c422fe32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "afbede92-27e8-4ee7-8f04-0548676a2fac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad6fa5e5-d1ad-4025-a044-d7f03a6b2b52",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7fc97525-d271-4dfa-a729-199ac4648b62",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "128c1e8c-d5b4-4001-9b37-289786354051",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "aa9b896f-3680-4efc-b5b0-51c812581f40",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0aab1951-92c8-44a2-9196-def3b77fd789",
                "ordinal": 3
              }
            ],
            "lineageTag": "0f0b5192-7a43-4ba9-a51f-630275e1ea20"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b342c3f5-63be-4303-a125-386ccd1bfde8",
        "partitions": [
          {
            "name": "DateTableTemplate_4bec28dd-0ea3-48ea-baaf-385204515e56",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d7c68dc3-6768-4511-b150-83cfae3b35d9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b737744f-ebb2-4199-b599-b92869424380",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2fad0a89-fd15-4dca-9506-0cbdc6d18728",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f88ada2f-5769-4137-a5f7-83f440f9cd4a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ce9937b4-d9a2-4bae-af96-202d98a9f518",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fa518a5f-73bc-4f9c-905e-be1bf9360646",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f163c619-455d-4ced-a0d8-611ea56e8299",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bdb98dc8-00c7-4a66-928b-f2355298f042",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bd4652a9-e3c7-44b2-b639-05832abda9a8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7f4e3478-7251-434b-b713-19acdc491639",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "305c27ec-3d3c-4da2-a8f5-02dec4613217",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f4589b23-77e4-4e83-aa25-8c1146a23e13",
                "ordinal": 3
              }
            ],
            "lineageTag": "f2ab0d1e-2a28-453b-91ee-1853b61254b1"
          }
        ],
        "isHidden": true,
        "lineageTag": "dfc5d434-e81e-4fd8-b484-369708ee7607",
        "partitions": [
          {
            "name": "LocalDateTable_d7c68dc3-6768-4511-b150-83cfae3b35d9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('order_activity'[order_purchase_timestamp])), 1, 1), Date(Year(MAX('order_activity'[order_purchase_timestamp])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}